nvim_colorscheme=rose-pine
htop_scheme=7
preferred_accent=yellow
base=#191724
surface=#1f1d2e
overlay=#26233a
muted=#6e6a86
subtle=#908caa
text=#e0def4
red=#eb6f92
redDim=#c04a6e
yellow=#f6c177
yellowDim=#d4a844
orange=#ebbcba
orangeDim=#c49896
blue=#31748f
blueDim=#245568
cyan=#9ccfd8
cyanDim=#74a8b0
magenta=#c4a7e7
magentaDim=#9c7ec0
highlightLow=#21202e
highlightMed=#403d52
highlightHigh=#524f67
