nvim_colorscheme=carbonfox
htop_scheme=7
preferred_accent=blue
base=#161616
surface=#252525
overlay=#2e2e2e
muted=#7b7c7e
subtle=#a4a5a7
text=#f2f4f8
red=#ee5396
redDim=#b5346d
yellow=#08bdba
yellowDim=#078f8d
orange=#3ddbd9
orangeDim=#269f9d
blue=#78a9ff
blueDim=#4d72b2
cyan=#33b1ff
cyanDim=#237cb2
magenta=#be95ff
magentaDim=#8c6ebd
highlightLow=#202020
highlightMed=#353535
highlightHigh=#4a4a4a
