nvim_colorscheme=zenbones
htop_scheme=7
preferred_accent=cyan
base=#1c1917
surface=#2a2522
overlay=#403833
muted=#7f746b
subtle=#a79f97
text=#b4bdc3
red=#de6e7c
redDim=#a6535e
yellow=#b77e64
yellowDim=#895f4c
orange=#b77e64
orangeDim=#895f4c
blue=#6099c0
blueDim=#48738f
cyan=#66a5ad
cyanDim=#4d7c82
magenta=#b279a7
magentaDim=#855b7d
highlightLow=#171412
highlightMed=#403833
highlightHigh=#5a4f48
