dpi-aware=no
font=NotoSans Nerd Font:weight=normal:size=24
fields=name,generic,comment,categories,filename,keywords
width=50
terminal=kitty
prompt="❯ "
show-actions=yes
exit-on-keyboard-focus-loss=no

[border]
radius=10

[dmenu]
exit-immediately-if-empty=yes

[colors]
background=#191724ff
text=#e0def4ff
prompt=#e0def4ff
placeholder=#6e6a86ff
input=#e0def4ff
match=#ebbcbaff
selection=#403d52ff
selection-text=#e0def4ff
selection-match=#ebbcbaff
counter=#f6c177ff
border=#ebbcbaff

# Rose Pine Dawn
# [colors]
# background=#faf4edff
# text=#575279ff
# prompt=#575279ff
# placeholder=#9893a5ff
# input=#575279ff
# match=#d7827eff
# selection=#dfdad9ff
# selection-text=#575279ff
# selection-match=#d7827eff
# counter=#ea9d34ff
# border=#d7827eff

# Rose Pine Moon
# [colors]
# background=#232136ff
# text=#e0def4ff
# prompt=#e0def4ff
# placeholder=#6e6a86ff
# input=#e0def4ff
# match=#ea9a97ff
# selection=#44415aff
# selection-text=#e0def4ff
# selection-match=#ea9a97ff
# counter=#f6c177ff
# border=#ea9a97ff
