include themes/rose-pine.conf

font_family family='RobotoMono Nerd Font Mono' postscript_name=RobotoMonoNFM-Th
bold_font family='RobotoMono Nerd Font Mono' style=Regular
italic_font family='RobotoMono Nerd Font Mono' style='Thin Italic'
bold_italic_font family='RobotoMono Nerd Font Mono' style=Italic

font_size 12.0

confirm_os_window_close 0

window_padding_width 0 1

tab_bar_edge top
tab_bar_style separator
tab_separator " "
active_tab_foreground #f6c177
active_tab_background #191724
active_tab_font_style normal
tab_bar_margin_width 1

copy_on_select yes

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+alt+enter new_window
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+alt+t new_tab
map ctrl+shift+d detach_tab ask
map ctrl+shift+m detach_tab
