nvim_colorscheme=kanagawa-dragon
htop_scheme=7
preferred_accent=blue
base=#181616
surface=#282727
overlay=#393836
muted=#727169
subtle=#a6a69c
text=#c5c9c5
red=#c4746e
redDim=#8f514d
yellow=#c4b28a
yellowDim=#8f8065
orange=#b6927b
orangeDim=#856b5a
blue=#8ba4b0
blueDim=#657882
cyan=#8ea4a2
cyanDim=#687976
magenta=#a292a3
magentaDim=#776d78
highlightLow=#22211f
highlightMed=#393836
highlightHigh=#625e5a
