nvim_colorscheme=lume
htop_scheme=7
preferred_accent=magenta
base=#12101e
surface=#1e1a2c
overlay=#262236
muted=#7e7896
subtle=#b0a8c4
text=#d8d0e4
red=#c49080
redDim=#9a6f66
yellow=#c4b080
yellowDim=#968563
orange=#e8b4a0
orangeDim=#b88e7f
blue=#8cc0e0
blueDim=#6d98b3
cyan=#88c0b8
cyanDim=#68938d
magenta=#b8a0e0
magentaDim=#8d79ad
highlightLow=#1e1a2c
highlightMed=#262236
highlightHigh=#302c42
