nvim_colorscheme=tokyonight-night
htop_scheme=7
preferred_accent=blue
base=#1a1b26
surface=#24283b
overlay=#343b58
muted=#565f89
subtle=#a9b1d6
text=#c0caf5
red=#f7768e
redDim=#b85769
yellow=#e0af68
yellowDim=#a6814d
orange=#ff9e64
orangeDim=#bd754a
blue=#7aa2f7
blueDim=#5977b5
cyan=#7dcfff
cyanDim=#5c9bbb
magenta=#bb9af7
magentaDim=#8a71b5
highlightLow=#1f2335
highlightMed=#33467c
highlightHigh=#3b4261
