# tailwindcss.
FROM docker.io/library/node:22-alpine

ARG TAILWINDCSS_LANGUAGE_SERVER_VERSION

RUN --mount=type=secret,id=company_ca,required=false \
    if [ -r /run/secrets/company_ca ]; then export NODE_EXTRA_CA_CERTS=/run/secrets/company_ca; fi; \
    npm install -g --omit=dev \
      "@tailwindcss/language-server@${TAILWINDCSS_LANGUAGE_SERVER_VERSION}" \
 && npm cache clean --force

ENTRYPOINT ["tailwindcss-language-server", "--stdio"]
