nvim_colorscheme=terafox
htop_scheme=7
preferred_accent=cyan
base=#000000
surface=#1d3337
overlay=#254147
muted=#6d7f8b
subtle=#cbd9d8
text=#e6eaea
red=#e85c51
redDim=#c54e45
yellow=#fda47f
yellowDim=#d78b6c
orange=#ff8349
orangeDim=#d96f3e
blue=#5a93aa
blueDim=#4d7d90
cyan=#a1cdd8
cyanDim=#89aeb8
magenta=#ad5c7c
magentaDim=#934e69
highlightLow=#0f1c1e
highlightMed=#293e40
highlightHigh=#425e5e
