nvim_colorscheme=poimandres
htop_scheme=7
preferred_accent=cyan
base=#1b1e28
surface=#303340
overlay=#42675a
muted=#767c9d
subtle=#a6accd
text=#e4f0fb
red=#d0679d
redDim=#8f476d
yellow=#fffac2
yellowDim=#b5b18a
orange=#fcc5e9
orangeDim=#b48da7
blue=#add7ff
blueDim=#91b4d5
cyan=#5de4c7
cyanDim=#5fb3a1
magenta=#fae4fc
magentaDim=#d0679d
highlightLow=#171922
highlightMed=#303340
highlightHigh=#506477
