nvim_colorscheme=mellow
htop_scheme=7
preferred_accent=blue
base=#161617
surface=#1b1b1d
overlay=#2a2a2d
muted=#757581
subtle=#9998a8
text=#c9c7cd
red=#f5a191
redDim=#b8756a
yellow=#e6b99d
yellowDim=#aa8873
orange=#ea83a5
orangeDim=#ab6078
blue=#aca1cf
blueDim=#81799b
cyan=#90b99f
cyanDim=#6b8b77
magenta=#e29eca
magentaDim=#a97698
highlightLow=#18181a
highlightMed=#353539
highlightHigh=#57575f
