nvim_colorscheme=no-clown-fiesta
htop_scheme=7
preferred_accent=blue
base=#000000
surface=#282828
overlay=#2b2b2b
muted=#727272
subtle=#afafaf
text=#e1e1e1
red=#b46958
redDim=#844d41
yellow=#f4bf75
yellowDim=#b08a57
orange=#ffa557
orangeDim=#ba7941
blue=#bad7ff
blueDim=#7e97ab
cyan=#88afa2
cyanDim=#658379
magenta=#aa759f
magentaDim=#7d5675
highlightLow=#2b2b2b
highlightMed=#373737
highlightHigh=#474d50
