nvim_colorscheme=moonfly
htop_scheme=7
preferred_accent=blue
base=#000000
surface=#171717
overlay=#303030
muted=#7c8c98
subtle=#b2b2b2
text=#bdbdbd
red=#ff5454
redDim=#ba3d3d
yellow=#e3c78a
yellowDim=#a89465
orange=#de935f
orangeDim=#a46d46
blue=#80a0ff
blueDim=#5e76bb
cyan=#8cc85f
cyanDim=#679344
magenta=#cf87e8
magentaDim=#975fa9
highlightLow=#171717
highlightMed=#303030
highlightHigh=#5f5f5f
