nvim_colorscheme=everforest
htop_scheme=7
preferred_accent=cyan
base=#000000
surface=#2e383c
overlay=#374145
muted=#7a8478
subtle=#9da9a0
text=#d3c6aa
red=#e67e80
redDim=#aa5d5f
yellow=#dbbc7f
yellowDim=#9f895d
orange=#e69875
orangeDim=#a86f56
blue=#7fbbb3
blueDim=#5f8c86
cyan=#83c092
cyanDim=#62906d
magenta=#d699b6
magentaDim=#9e7185
highlightLow=#1e2326
highlightMed=#414b50
highlightHigh=#495156
